### ISSUE TITLE
Adding Backup Server Name as variable

### ISSUE THREAD

**Issue by jon-rei** [lehuizi/ah_borg_backup#1]
Today i got myself a storage box from Hetzner.
There i noticed that the server names changed from your-backup.de to your-storagebox.de
Maybe you should add a variable to change the server name.

I know you can just change the line at the bottom. But it would be neat to use a variable there.

Regards Jonas

**Comment by alxhlz** [comment]
I don't use the script just with Hetzners storage box, so i change the repository for every server I want to backup. In my opinion it's easy enough to change this in the repository export.

Best regards,
Alex
